import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-2">
          <div className="w-[120px]">
            <Link href="/dashboard/account" className="p-2 bg-blue-500 text-white">Account</Link>
          </div>
          <div className="flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
